# Generated by Django 5.2.15 on 2026-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_grade_branch'),
        ('transport', '0003_vehicle_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='stop_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('SCHOOL', 'School')], default='REGULAR', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['stop_type'], name='transport_s_stop_ty_b80733_idx'),
        ),
    ]
