# Generated by Django 5.2.15 on 2026-09-03 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_alter_schooldocumenttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='school.branch'),
        ),
    ]
